.\" $Id: bproc_chgrp.2,v 1.1 2004/09/08 20:28:44 mkdist Exp $
.TH BPROC_CHGRP 2 "" "BProc 4.0.0pre8" "BProc Programmer's Manual"
.SH NAME
bproc_chgrp \- change node group ownership
.SH SYNOPSIS
\fB#include <sys/bproc.h>\fR

int \fBbproc_chgrp\fR(int \fInode\fR, int \fIgroup\fR);

.SH DESCRIPTION
.PP
\fBbproc_chgrp\fR changes the group of \fInode\fR to \fIgroup\fR.  A
process can change the group to any group that that process is a
member of.

.SH RETURN VALUE
.PP
On success, \fBbproc_chgrp\fR will return 0.  On error,
\fBbproc_chgrp\fR will return \-1 and errno will be set
appropriately.

.SH ERRORS
.PP
TP
\fBEPERM\fR
The calling process isn't permitted to change the
\fInode\fR's group or the caller isn't a member of \fIgroup\fR.
.TP
\fBEINVAL\fR
\fInode\fR is an invalid node number or
\fInode\fR is down.
.TP
\fBEBUSY\fR
The BProc system is not running.

.SH SEE ALSO
.PP
\fBbproc_access\fR(2),
\fBbproc_chmod\fR(2),
\fBbproc_chown\fR(2),
\fBbproc_nodeinfo\fR(2)
