.TH BPROC_NODELIST 2 "" "BProc 4.0.0pre8" "BProc Programmer's Manual"
.SH NAME
bproc_nodelist \- get status information for all the nodes
.SH SYNOPSIS
\fB#include <sys/bproc.h>\fR

int \fBbproc_nodelist\fR(struct bproc_node_set_t * \fIns\fR);

.SH DESCRIPTION
.PP
\fBbproc_nodelist\fR fills in a \fBstruct bproc_node_set_t\fR with
information for every node in the system.  The nodeset 

structures \- one for every node in the system.  A
pointer to this list is stored in the pointer pointed to by the
\fIlist\fR parameter.  The return value is the number of
elements in the list.  The memory for the list is allocated using
\fBmalloc\fR and it is up to the caller to free this
memory.

Calling \fBbproc_nodelist\fR will be faster than calling
\fBbproc_nodestatus\fR on every function.

.SH RETURN VALUE
.PP
On success, \fBbproc_nodelist\fR will return the number of elements in
the node set.  On error, it will return \-1 and errno will be
set appropriately.


.SH ERRORS
.TP
\fBEBUSY\fR
The BProc system is not running.

.SH SEE ALSO
.PP
\fBbproc_nodeinfo\fR(2)

